version: 2

before:
  hooks:
    - go mod download

builds:
  - id: slik
    main: ./cmd/slik/main.go
    binary: slik
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: slurmabler
    main: ./cmd/slurmabler/main.go
    binary: slurmabler
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    goos:
      - linux
    goarch:
      - amd64
      - arm64

release:
  draft: false
