slik:
  repository: quay.io/invirtuate/slurm/slik
  tag: latest-amd64
  resources:
    requests:
      memory: "1Gi"
    limits:
      memory: "2Gi"
  logging:
    debug: true
    path: ./
    encoding: console
  probes_api:
    listen: 0.0.0.0
    port: 9093

slurm:
  slurmabler:
    image: "quay.io/invirtuate/slurm/slurmabler:v0.0.0-amd64"
    service_account: "slik"
  munged:
    image: "quay.io/invirtuate/slurm/munged:v0.0.0-amd64"
  slurmctld:
    image: "quay.io/invirtuate/slurm/slurmctld:v0.0.0-amd64"
  slurmd:
    image: "quay.io/invirtuate/slurm/slurmd:v0.0.0-amd64"
  slurm_toolbox:
    image: "quay.io/invirtuate/slurm/toolbox:v0.0.0-amd64"
  mariadb:
    image: "mariadb:11.4.2-noble"
  slurmdbd:
    image: "quay.io/invirtuate/slurm/slurmdbd:v0.0.0-amd64"
  slurmrestd:
    image: "quay.io/invirtuate/slurm/slurmrestd:v0.0.0-amd64"